### ISSUE TITLE
Add multiple namespace support 

### ISSUE THREAD

**Issue by viveksyngh** [openfaas/faas-idler#37]
Add multiple namespace support 

## Expected Behaviour

Function names in faas-idler are not namespace aware. As other components now support multiple namespaces it is required for faas-idler to be namespace aware. 

## Current Behaviour

Does not support multiple namespace.

## Possible Solution

Implement a similar logic as SDK-Connector to make this namespace awar.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?

* Operating System and version (e.g. Linux, Windows, MacOS):

* Link to your project or a code example to reproduce issue:

* Please also follow the [troubleshooting guide](https://github.com/openfaas/faas/blob/master/guide/troubleshooting.md) and paste in any other diagnostic information you have:

**Comment by viveksyngh** [comment]
While I was adding multiple namespace support for `faas-idler`I see there are some challenges with how we collect the metrics. Right now there are two ways a function deployed in default namespace (it is openfaas-fn but can be overriden ) can be invoked. 
    * One without namespace suffix like http://127.0.0.1:31112/function/filget
    * One with namespace suffix like http://127.0.0.1:31112/function/figlet.openfaas-fn
 
Now both of these invocation metrics get recorded with different function names in prometheus. One with name `figlet` and other with name `figlet.openfaas-fn`.  `faas-idler` can not treat them differently. To solve this problem we have two option in opinion.
 
1. Have a default namespace configuration in `faas-idler` and merge `figlet` and `figlet.namespace` metrics in one for default namespace. 
2. Invoke all the functions with `functionName.namesapce` even for default namespace ` so that we have metrics recorded with single function name.  
 
I am looking for suggestion on both of these approach and if I am missing something.

**Comment by DrkDigglr** [comment]
Having spotted this issue earlier this year (https://github.com/openfaas-incubator/faas-idler/issues/36) I think option is preferable, as it doesn't affect the current method of invoking functions in the default namespace. I.e. you don't need to append the namespace.

**Comment by alexellis** [comment]
@viveksyngh 
Other than `` and ``openfaas-fn` having an issue, is there any problem with the explicitly override namespaces?

I.e. `staging` or `prod` as a namespace?

**Comment by viveksyngh** [comment]
It should but there are some changes also required for that which should get merged 

1. The Replica count exporter need to fetch the replicas from multiple namespace and store that in promethes
2. `faas-idler` also need to fetch functions from multiple namespaces and build the map

**Comment by alexellis** [comment]
Can you start a PR to work on 2?

I see why 1) is required for the default vs empty namespace, why is it required for faas-idler? Does the /system/function/name endpoint not give proper replicas yet for multiple-namespaces?

**Comment by viveksyngh** [comment]
I think I already have changes required for 2 in some branch, I will find that and raise a PR if I have not done already. May be I did not raise PR because I was waiting for 1 changes to get merged. 


I think my PR for 1 has combined two features. (https://github.com/openfaas/faas/pull/1488)

 * To solved the issue with default vs empty namespace 

* The ticker which runs to update the replicas count for every function needs to fetch functions from all namespaces in order provides replicas count for all functions. 

I can double check if 2nd part in required or not. But I guess it was required that is the reason I did that change.

**Comment by aarlint** [comment]
Hey @viveksyngh how is this coming along?  Im working on a project that would benefit from this feature over the next two weeks.  Is there an end in sight?

**Comment by viveksyngh** [comment]
@aarlint I have already created PR for this to fix faas-idler and I am testing it. I should have it tested and ready by the end of this week.

**Comment by alexellis** [comment]
PR: #41

**Comment by viveksyngh** [comment]
@alexellis I have create a fresh PR for this and tested it. 

PR #42 

@aarlint let me know if you can help with the testing for this PR ?

**Comment by goggi** [comment]
@viveksyngh 
I have deployed your PR to my dev cluster and so far its working good!

**Comment by viveksyngh** [comment]
@goggi I have done some update on the PR. can you please try the updated one and let us know if it is working as expected 
?

**Comment by goggi** [comment]
great! I will let it run on my dev server for a couple of days and report if I have any issues.
